### PR TITLE
Update to be compatible with Node 16

### PR DESCRIPTION
**Pull request by GingkathFox**
Ended up being three lines to remove.

Done on `Linux 5.13.7-arch1-1 #1 SMP PREEMPT Sat, 31 Jul 2021 13:18:52 +0000 x86_64 GNU/Linux`

### CODE REVIEW

**Comment by fredkilbourn** [comment]
Looking forward to seeing this merged, nice work!

**Comment by Milo123459** [comment]
Vital for DJS' V13! Great work

**Comment by DraftProducts** [comment]
Is there an approximative date for the merge?

**Comment by GingkathFox** [comment]
@DraftProducts Most likely not since discord hasn't looked at this repo in a year, I'm thinkin of just making my fork the "main" active repo

**Comment by Milo123459** [comment]
> @DraftProducts Most likely not since discord hasn't looked at this repo in a year, I'm thinkin of just making my fork the "main" active repo

Please do! Maybe publish it as an npm package rather than having to install via git!

**Comment by DraftProducts** [comment]
Maybe a ping to jasoncitron ? He is the biggest contributor🤔

**Comment by NMW03** [comment]
You can install GingkathFox's repo with `npm i GingkathFox/erlpack`

**Comment by GingkathFox** [comment]
> > @DraftProducts Most likely not since discord hasn't looked at this repo in a year, I'm thinkin of just making my fork the "main" active repo
> 
> Please do! Maybe publish it as an npm package rather than having to install via git!

@Milo123459 you can `npm i GingkathFox/erlpack`

**Comment by fredkilbourn** [comment]
Maybe open an issue on discord repo and reference this?

**Comment by SemperFortis** [comment]
Hi guys, I've also wanted to know the status of this but I got a bit bored of waiting and decided to explore it on my own. I rewrote it to Typescript with browser support. Here's the [repo](https://github.com/SemperFortis/erlpackjs) if you guys want to check it out.

**Comment by DraftProducts** [comment]
> Hi guys, I've also wanted to know the status of this but I got a bit bored of waiting and decided to explore it on my own. I rewrote it to Typescript with browser support. Here's the [repo](https://github.com/SemperFortis/erlpackjs) if you guys want to check it out.

It's a nice project, but I don't think that your package will give the same perfs as the official package with bindings 🤔

**Comment by Milo123459** [comment]
@jasoncitron could you take a look at this?

**Comment by fredkilbourn** [comment]
@jhgg @adill @zorkian @mezz @fozzle @samschlegel @night - tagging some more discord people that are contributors, this is blocking full optimization with the new discord.js v13 library, which requires node v16, which requires this pull (or similar) to work.

**Comment by DraftProducts** [comment]
We are now waiting about 10 days for this merge, I would make a fork of the PR repo.
Thanks @GingkathFox for the work 👍

**Comment by GingkathFox** [comment]
Oh wow it's been 10 days already

Ig move to my fork?

**Comment by GingkathFox** [comment]
I've put in a ticket to detatch my fork from the main repo

**Comment by Milo123459** [comment]
Your fork / published package doesn't work with DJS as it simply won't pick up your erlpack package.

**Comment by Milo123459** [comment]
Also I think it's a bit scummy to make a PR changing who maintains the repo. Also remove the pnpm lock

**Comment by icdevin** [comment]
This has no chance of being accepted as it exists now since it tells users to install his own repo and changes the name and author/maintainers...if you're going to spin off your own, do so and tell people but it would've been wiser to leave this PR with just the changes needed for Node v16.

**Comment by Milo123459** [comment]
At this rate, either fix the PR with only needed changes, or someone make a new PR. It just makes no sense, changing the author, name, readme, etc to the name of your fork then attempting to make that change in the main repo? Doesn't make sense to me. Please revert to just needed changes

**Comment by fredkilbourn** [comment]
To be honest the best solution would be discord.js forking and maintaining this and not leaving users to fight for a fix.  I've added an issue over there making the suggestion: https://github.com/discordjs/discord.js/issues/6418  upvote over there if you agree.

**Comment by jhgg** [comment]
Well you took a mergeable PR and made it totally unmergable. Feel free to re open with the original change set.

**Comment by Milo123459** [comment]
Oh for gods sake :(

**Comment by GingkathFox** [comment]
Oh whoops, I'll re-push with the proper fixes, didn't realize that would affect it

**Comment by Milo123459** [comment]
> Oh whoops, I'll re-push with the proper fixes, didn't realize that would affect it
> 
> I like how this happens after everything lol

Not trying to be rude but how could you *not* see how this wouldn't affect it?

- Change Authors
- Renamed
- Add a pnpm-lock (unneeded)
- Then proceeded to make the main repo look like the fork?

**Comment by GingkathFox** [comment]
> > Oh whoops, I'll re-push with the proper fixes, didn't realize that would affect it
> 
> > 
> 
> > I like how this happens after everything lol
> 
> 
> 
> Not trying to be rude but how could you *not* see how this wouldn't affect it?
> 
> 
> 
> - Change Authors
> 
> - Renamed
> 
> - Add a pnpm-lock (unneeded)
> 
> - Then proceeded to make the main repo look like the fork?

I didn't realize my fork was edited on the master, I thought it had created a new branch with the fixes

**Pull request closed without merging**
