### PR TITLE
Redo node 16 support

### PR DESCRIPTION
**Pull request by GingkathFox**
Didn’t move to a new branch in #40, fixed here without extraneous changes

### CODE REVIEW

**Comment by GingkathFox** [comment]
Gonna update packages too, don’t merge yet (or merge then merge #41, which also updates the packages)

**Comment by GingkathFox** [comment]
@icdevin sorry for the earlier mixup

**Comment by promise** [comment]
It seems pointless to have two PRs fixing the same issue, and if you're going to also update packages then this is pretty much a copy of #41. Merging both PRs will also have an unnecessary conflict as they have the same changes. Resolving the conflict and merging both PRs will only confuse and has the same effect as merging one and closing the other one.

I would suggest closing this and keep #41 but feel free to wait for a maintainer to give their input instead.

**Comment by jhgg** [comment]
Closing as dupe of #41

**Pull request closed without merging**
