### PR TITLE
feat: Compatibility for Node 16

### PR DESCRIPTION
**Pull request by icdevin**
Originally from https://github.com/Hazmi35

### CODE REVIEW

**Comment by icdevin** [comment]
@jhgg These are the original changes from the other 2 closed PRs.

**Comment by promise** [comment]
Reinstalling node-gyp *should* resolve compiling issues with node v16. Try `npm ui -g node-gyp && npm i -g node-gyp`.
Me myself, and a friend of mine, have gotten it working doing this although we're not entirely sure if it will work for everyone.

It also looks like this is a dupe of #41, or the other way around. (#41 was reopened half an hour after this PR was made)
Seeing as this PR originates from #41's author, I'd suggest closing this and instead having #41, but I'm not a maintainer so feel free to wait for a maintainer to give their input.

**Comment by wrac4242** [comment]
> Reinstalling node-gyp _should_ resolve compiling issues with node v16. Try `npm uni -g node-gyp && npm i -g node-gyp`.
> Me myself, and a friend of mine, have gotten it working doing this although we're not entirely sure if it will work for everyone.
> 
> It also looks like this is a dupe of #41, or the other way around. (#41 was reopened half an hour after this PR was made)
> Seeing as this PR originates from #41's author, I'd suggest closing this and instead having #41, but I'm not a maintainer so feel free to wait for a maintainer to give their input.

Hi, the given command does not work for me, I still get the same compiling error trying to reinstall erlpack
uname output `Linux wrac-fedora 5.13.9-200.fc34.x86_64 #1 SMP x86_64 GNU/Linux`

**Comment by icdevin** [comment]
@promise Agreed. Since he reopened it, I’ll shut this.

**Comment by fredkilbourn** [comment]
That command didn't fix things for me, either.

**Comment by promise** [comment]
Apologies, probably me having issues then.

**Pull request closed without merging**
